version: '3'

services:

  mongodb:
    image:  mongo:latest
    container_name: containerized-mongo-database
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
#      - "./data:/data/db"
      - type: volume
        source: host-mongo-data
        target: "/data/db"

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: containerized-mongo-express-server
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  host-mongo-data:

#networks:
#  mongo-network:
